In [1]:
import numpy as np

In [2]:
x = np.array([[0, 1], [2, 3], [4, 5]])

In [3]:
print(x)

[[0 1]
 [2 3]
 [4 5]]


In [4]:
y = np.array([10, 20])

In [5]:
print(y)

[10 20]


In [6]:
print(x * y)

[[  0  20]
 [ 20  60]
 [ 40 100]]


In [7]:
x

array([[0, 1],
       [2, 3],
       [4, 5]])

In [8]:
x[0, 1]

1

In [9]:
x[0][1]

1

In [10]:
x[0][1] = 10

In [11]:
x

array([[ 0, 10],
       [ 2,  3],
       [ 4,  5]])