In [1]:
import numpy as np

In [2]:
a = np.array([10,20,30,40,50])
a[2]=99
print(a)

[10 20 99 40 50]


In [3]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
b[1,2]

6

In [11]:
data = np.array([0,10,20,30,40])
print(data[2:-1])

[20 30]


In [13]:
a = np.array([[10,20,30],[40,50,60],[70,80,90]])
print(a)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [22]:
print(a[0:2,0:2])

[[10 20]
 [40 50]]


In [27]:
a = np.array([[10,20,30],[40,50,60]])
for i, item in np.ndenumerate(a):
    print(f"{i}の要素は{item}です。")

(0, 0)の要素は10です。
(0, 1)の要素は20です。
(0, 2)の要素は30です。
(1, 0)の要素は40です。
(1, 1)の要素は50です。
(1, 2)の要素は60です。


In [29]:
a = np.array([-2,-1,0,1,2])
print(a[a>=0])

[0 1 2]


In [34]:
print(a[~(a%2 == 0)])

[-1  1]


In [41]:
a = np.array([3,1,0,4,2])
a_descend = np.sort(a)[::-1]
a_descend

array([4, 3, 2, 1, 0])

In [44]:
A = np.array([10,20,30,40])
print(A/2)

[ 5. 10. 15. 20.]


In [47]:
A = np.array([[56,45,83],[67,59,41]])
print(np.sum(A))

351


In [52]:
print(np.mean(A))

58.5


In [60]:
data = np.random.randint(56)
print(data)

32


In [55]:
print(data.mean())
print(data.std())

-0.11198444710528499
1.0518426923505408


In [62]:
A = np.array([[10,20],[30,40]])
B = np.array([[5,5],[5,5]])
C = A + B
print(C)

[[15 25]
 [35 45]]


In [64]:
D = A * B
print(D)

[[ 50 100]
 [150 200]]


In [65]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[100],[200]])
C = A+B
C


array([[101, 102, 103],
       [204, 205, 206]])