In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
b = np.array((1,2,3))

In [3]:
print(a,b)

[1 2 3] [1 2 3]


In [4]:
c = np.array([1, 2, 3.5], dtype=int)
print(c)

[1 2 3]


In [7]:
d = np.array([9.123, 10.5, 12.11], dtype="<U4")
print(d)

['9.12' '10.5' '12.1']


In [14]:
a = np.array([1,2,3,4,5,6])
a = a.reshape(2,3)
print(a)

[[1 2 3]
 [4 5 6]]


In [15]:
a.flatten()

array([1, 2, 3, 4, 5, 6])

In [16]:
a= a.reshape(3,2)

In [18]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [17]:
len(a)

3

In [22]:
a = np.array(["dog", "cat", "bird"])
b = np.insert(a, 0, "snake")
print(b)

['snak' 'dog' 'cat' 'bird']


In [23]:
a = np.array(["dog", "cat", "bird"])
b = np.delete(a, 2)
print(b)

['dog' 'cat']
